### ISSUE TITLE
停止共享

### ISSUE THREAD

**Issue by topazur** [pili-engineering/QNRTC-Web#106]
![image](https://user-images.githubusercontent.com/88650465/142832638-1bf697ee-8c01-47ad-aed8-475b60101386.png)
用户手动停止共享，有没有监听函数，目前仅打印警告

**Comment by yaox023** [comment]
可以监听 track 对象的 ended 事件来获取这个信息

> ![image](https://user-images.githubusercontent.com/88650465/142832638-1bf697ee-8c01-47ad-aed8-475b60101386.png) 用户手动停止共享，有没有监听函数，目前仅打印警告
