### ISSUE TITLE
Uncaught (in promise) TypeError: r.webkitGetUserMedia is not a function

### ISSUE THREAD

**Issue by foolishma** [pili-engineering/QNRTC-Web#120]
An error occurs when the following statement is executed:
const localTracks = await QNRTC.createMicrophoneAndCameraTracks();

Excuse me, what is the reason and how to solve it?

**Comment by yydounai1234** [comment]
getUserMedia is available only in https or localhost, please check it.
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
