### ISSUE TITLE
小程序集成七牛云实时音视频的问题

### ISSUE THREAD

**Issue by meifangwen** [pili-engineering/QNRTC-Web#131]
您好，就是咨询一下，目前我需要在小程序端通过H5的web-view网页的方式去实现七牛云实时音视频，我用的是七牛云的WEB端 SDK，目前都不知道有什么思路去集成，就是您有做过吗，能提供一下实现思路吗，谢谢啦

**Comment by ryuujo1573** [comment]
按照微信内网页开发的思路去集成就可以，如果在小程序<web-view>内不需要微信的API，则开发方式和一般的网页开发是一致的
