### ISSUE TITLE
chrome 69 报错

### ISSUE THREAD

**Issue by voids** [pili-engineering/QNRTC-Web#17]
系统：macOS 10.13
浏览器：chrome 69
错误信息：
DOMException: Failed to execute 'addTransceiver' on 'RTCPeerConnection': This operation is only supported in 'unified-plan'. 'unified-plan' will become the default behavior in the future, but it is currently experimental. To try it out, construct the RTCPeerConnection with sdpSemantics:'unified-plan' present in the RTCConfiguration argument.

经测试，之前的chrome版本正常

**Comment by disoul** [comment]
已经修复，替换 pili-rtc-web 到 1.2.1, 或者使用本仓库最新的 Release 文件
