### ISSUE TITLE
vue2.5 + chrome 71 + SDK1.2.4 运行报错

### ISSUE THREAD

**Issue by aadd1989** [pili-engineering/QNRTC-Web#28]
rtc.publish(stream) 时，出现的错误
Uncaught (in promise) 1st argument is not instance of RTCPeerConnection.

**Comment by aadd1989** [comment]
![image](https://user-images.githubusercontent.com/10625335/50479776-3157ba00-0a13-11e9-8a8b-c2caa5d87fe1.png)

**Comment by disoul** [comment]
抱歉回复慢了，这个问题已经修复，原因是 SDK 依赖的上游库出现了不兼容升级
执行 `npm install pili-rtc-web@legacy` 安装最新的 `1.2.4` 修复版本即可解决

**Comment by aadd1989** [comment]
@disoul 🙏多谢
