### ISSUE TITLE
开启了https，谷歌上还是报错无法打开摄像头，火狐浏览器可以

### ISSUE THREAD

**Issue by Cxz-web** [pili-engineering/QNRTC-Web#29]
Uncaught (in promise) DOMException: Could not start audio source 报错信息是这个，火狐浏览器能正常进行

**Comment by disoul** [comment]
看报错是只有音频设备没法采集，能不能将你的 deviceInfo 贴一下
https://doc.qnsdk.com/rtn/web/docs/api_device_manager_track#0

然后火狐应该会手动让你选择麦克风，找到火狐选择的那个麦克风设备，将它的 deviceId 填入采集配置中再试试 https://doc.qnsdk.com/rtn/web/docs/api_device_manager_track#1

我怀疑是 chrome 默认可能选择了一个无效的音频设备

**Comment by Cxz-web** [comment]
感谢你的回答，
我看了下谷歌设置里面选择的音频设备和火狐的是一样的默认设备。
用谷歌打开页面的时候 右上角的摄像头也出来了， 里面的设备选的也是默认设备，请问是否还需要指定id呢？需要的话，晚点儿我再重新部署上去试试看。

**Comment by disoul** [comment]
1. localhost 时是不是也会报这个错
2. 取消音频采集只保留视频是否就恢复正常了
3. 取消视频采集只采集音频（这里最好指定一下 id）是否必现这个错误

如果这 3 个情况都满足，应该就是 Chrome 不支持这个麦克风设备，试一试换个设备
