### ISSUE TITLE
请问如何以低清晰度显示订阅的高清流？

### ISSUE THREAD

**Issue by fh345392977** [pili-engineering/QNRTC-Web#34]
订阅到的是1080P高清流，如何以720P调用play方法？

**Comment by disoul** [comment]
这种动态改变分辨率的需求肯定是要涉及到视频的重新编码的，无论是在服务端还是在客户端做这个操作都会对通信延迟有很大的影响，同时成本也很高

所以这种场景很抱歉我们无法支持

**Comment by fh345392977** [comment]
如果我要自己实现的话，七牛是否支持实时音视频转码？服务端转码后，能直接用这个sdk在客户端显示吗？

**Comment by disoul** [comment]
如果真的有这种需求，动态改变分辨率也不是最佳的选择，因为动态转码会有很大的延迟和成本。针对这种情况，我们正在实现 simulcast 的方案，也就是发布端同时发布不同码率的流，订阅端根据自己的情况选择自己合适的码率。

**Comment by fh345392977** [comment]
非常感谢
