### ISSUE TITLE
websdk连接到七牛云房间服务器的websocket断开了，close后会自动重连吗？

### ISSUE THREAD

**Issue by qugemingzizhenmafan** [pili-engineering/QNRTC-Web#35]
一定要刷新页面，再重新进入房间吗？

**Comment by cuyl** [comment]
因为网络原因signal断了SDK会尝试重连，不需要刷新页面。
收到 disconnect code 10004 时可以尝试重新走 joinRoom 逻辑
参考文档：
https://doc.qnsdk.com/rtn/web/docs/api_track_mode_session#22_6

**Comment by qugemingzizhenmafan** [comment]
那如果连接断开前我监听了各种事件，在sdk重连过程中，其他用户发布流取消发布流的这些事件，会不会在重连成功后监听到呢？同理，在重连超时后再次joinRoomWithToken又会如何呢？

**Comment by cuyl** [comment]
sdk重连后房间的变化连成功后能监听到。
disconnect触发之后（包括重连超时）会释放房间的所有信息，之后再 joinRoom 和上一次 joinRoom 没啥联系

**Comment by disoul** [comment]
简单来说，websocket 断开有 2 种状态：
- 断开后 SDK 会自动尝试重连，此时处于重连状态，可以通过 [room-state-change](https://doc.qnsdk.com/rtn/web/docs/api_track_mode_session#22_0) 这个事件感知
- 之后如果 SDK 重连失败（超时或者其他原因），会抛出 [disconnect](https://doc.qnsdk.com/rtn/web/docs/api_track_mode_session#22_6) ，此时房间已经处于不可恢复的断开状态了，SDK 会清空释放整个房间（但是你的事件监听不会被释放）

所以如果你在超时后再次重新 joinRoom 是没有问题的，事实上 Demo 也是[这么做](https://github.com/pili-engineering/QNRTC-Web/blob/master/Demo/src/stores/roomStore.ts#L493-L516)的

**Comment by qugemingzizhenmafan** [comment]
> 简单来说，websocket 断开有 2 种状态：
> 
> * 断开后 SDK 会自动尝试重连，此时处于重连状态，可以通过 [room-state-change](https://doc.qnsdk.com/rtn/web/docs/api_track_mode_session#22_0) 这个事件感知
> * 之后如果 SDK 重连失败（超时或者其他原因），会抛出 [disconnect](https://doc.qnsdk.com/rtn/web/docs/api_track_mode_session#22_6) ，此时房间已经处于不可恢复的断开状态了，SDK 会清空释放整个房间（但是你的事件监听不会被释放）
> 
> 所以如果你在超时后再次重新 joinRoom 是没有问题的，事实上 Demo 也是[这么做](https://github.com/pili-engineering/QNRTC-Web/blob/master/Demo/src/stores/roomStore.ts#L493-L516)的

第二种情况，监听事件一直不会被释放吗？还是监听到disconnect事件后执行完回调函数后再释放监听事件？

**Comment by disoul** [comment]
房间对象的监听事件除非用户手动调用 off/removeAllListeners 之类的方法释放，否则 SDK 是不会释放的。

**Comment by qugemingzizhenmafan** [comment]
okk, 谢谢两位大佬。
