### ISSUE TITLE
nom start 之后报错，麻烦处理一下

### ISSUE THREAD

**Issue by aiiaji** [pili-engineering/QNRTC-Web#38]
Failed to compile
/Users/aba/Downloads/QNRTC-Web-2.1.0/Demo/src/pages/settings.tsx
Type error: Type '{ children: Element[]; value: "288p" | "480p" | "540p" | "720p"; onChange: (e: any) => void; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Props'.  TS2322

    109 |       <Grid item container wrap="nowrap" justify="center" spacing={16}>
    110 |         <Grid item>
  > 111 |           <Select
        |            ^
    112 |             value={roomStore.selectVideoConfig}
    113 |             onChange={(e) => roomStore.setSelectVideoConfig(e.target.value as keyof publishVideoConfigs)}
    114 |           >

**Comment by cuyl** [comment]
这个问题在 #37 修复了，您下载新版的试试？
