### ISSUE TITLE
回音杂音问题

### ISSUE THREAD

**Issue by huangqizai** [pili-engineering/QNRTC-Web#44]
回音杂音怎么处理，你们echoCancellation和noiseSuppression不管用，有没有好的处理办法

**Comment by disoul** [comment]
能描述一下具体现象么？回音和杂音在正常设备和正常使用下一般是不会发生的，希望可以提供这些信息：
- 测试的时候是否 2 台设备隔得太近，导致麦克风重复录入音响的声音导致回声？
- 测试的时候是否开启本地麦克风的播放，导致和上面一样的问题？
- 杂音问题如果能稳定复现是否和麦克风设备有关，是否尝试过更换麦克风？
