### ISSUE TITLE
Chrome 更新到 74.0.3729.108 后没有navigator.mediaDevices

### ISSUE THREAD

**Issue by fh345392977** [pili-engineering/QNRTC-Web#45]
`navigator.mediaDevices`返回`undefined`，所以`navigator.mediaDevices.enumerateDevices()`报错了

**Comment by disoul** [comment]
![image](https://user-images.githubusercontent.com/8756894/56937478-7b6eba80-6b2f-11e9-9933-41ee459cade1.png)
并没有复现

**Comment by fh345392977** [comment]
http下被禁了
<img width="530" alt="屏幕快照 2019-04-30 14 24 42" src="https://user-images.githubusercontent.com/16329330/56943829-cef2ff80-6b53-11e9-8e04-ed9844706f2b.png">

**Comment by disoul** [comment]
![image](https://user-images.githubusercontent.com/8756894/56950210-804f6080-6b67-11e9-9d95-fdf41c781e89.png)

**Comment by fh345392977** [comment]
大哥，我的意思是别让他报错

**Comment by disoul** [comment]
了解了，我们下个版本修复一下。
