### ISSUE TITLE
编译报错v2.2.0

### ISSUE THREAD

**Issue by xudongjian** [pili-engineering/QNRTC-Web#47]
![image](https://user-images.githubusercontent.com/16408553/57213411-4ffd3b80-7019-11e9-9272-90d2c4893e83.png)

**Comment by disoul** [comment]
应该是你 typescript 版本过老了，试试更新一下 typescript 版本

**Comment by brucebnu** [comment]
这个不是按照项目package.json里typescript的版本走的吗？
