### ISSUE TITLE
ws里很多restart消息，无法推拉流，请问是什么原因呢？

### ISSUE THREAD

**Issue by fh345392977** [pili-engineering/QNRTC-Web#49]
正常能推拉流的ws消息长这个样子
<img width="629" alt="屏幕快照 2019-05-24 16 43 49" src="https://user-images.githubusercontent.com/16329330/58315135-7ad1f700-7e43-11e9-9f38-747fea487635.png">
但今天客户公司在他们的网络环境下，用他们提供的win7 sp1联想笔记本，Chrome 73，无法推拉流，ws里一直都是`***-restart`的消息。同样的网络下，我用ipad的safari和chrome可以推拉流(chrome不能推，可能是权限问题)，app可以推拉流。

我开始以为是win7有问题，但回来后自己装了个win7，是好的，可以推拉流。

所以想问一下，一直出现`***-restart`消息是啥原因？准备从这方面入手。

**Comment by fh345392977** [comment]
仔细琢磨了一下，我猜可能是他们公司网络做了直播或者流媒体方面的限制，所以七牛的直播服务一下`restart`

**Comment by geograous** [comment]
你说的是有可能的，`***-restart` 有好几种，看你的描述，可能是连麦时的。

**Comment by fh345392977** [comment]
> 你说的是有可能的，`***-restart` 有好几种，看你的描述，可能是连麦时的。

让他们切换了网络，就可以看到直播了。
