### ISSUE TITLE
node 6.x版本中，执行npm run start报错。Module parse failed: Unexpected token (1:61399)

### ISSUE THREAD

**Issue by buyixiaojiang** [pili-engineering/QNRTC-Web#50]
安装的是2.2.0版本，定位到第1行第61399列后是`const r={...e}`，2.2.1版本也是报错，2.2.0-alpha.4版本是正常的。
扩展运算符在Node 6.x版本中暂不支持。

**Comment by geograous** [comment]
现在一般都使用 node 8 了，升级到 node 8 或者以上版本应该 ok 了，不行再来找我。本地开发环境的话一般先装一个 nvm 来管理 node 版本。

**Comment by buyixiaojiang** [comment]
我本地好调整，但是线上的服务器需要找运维来解决，我已经把版本降低到2.2.0-alpha.4。我的理解中，小版本的升级是兼容之前的版本。

**Comment by geograous** [comment]
之前有人提过，详见 https://github.com/pili-engineering/QNRTC-Web/issues/14
