### ISSUE TITLE
iOS上 12.3的 Safari 和 74的Chrome都无法拉取远端流

### ISSUE THREAD

**Issue by fh345392977** [pili-engineering/QNRTC-Web#51]
我用mac的Safari访问，获取到的远端流如下截图
<img width="747" alt="屏幕快照 2019-05-31 21 32 35" src="https://user-images.githubusercontent.com/16329330/58709077-e986f580-83eb-11e9-8bce-d4a728bf5cf4.png">
但在iOS上就是这样
<img width="925" alt="屏幕快照 2019-05-31 21 32 28" src="https://user-images.githubusercontent.com/16329330/58709088-f1df3080-83eb-11e9-87e2-03bdd2f9a4f7.png">
iOS上track为undefined，然后就报错了
<img width="489" alt="屏幕快照 2019-05-31 21 32 49" src="https://user-images.githubusercontent.com/16329330/58709109-00c5e300-83ec-11e9-867b-06c78d85a52e.png">
```
[Error] subscribe error – Error: piliRTC: unexpected error remote track not found
Error: piliRTC: unexpected error remote track not found
```
Chrome的调试日志我稍后放出

**Comment by geograous** [comment]
有日志吗？麻烦贴一下，出错应该在之前的步骤。原来的 safari 使用 plan b，最新的 safari （12.1.0之后）默认使用 unified plan，应该是这个原因导致的。可以尝试关闭图中的选项，应该就和原来一致了。
![image](https://user-images.githubusercontent.com/9160851/59730776-3be26600-9276-11e9-95c8-1ec34c73f27d.png)，我们会在之后的版本中修复这个问题。

**Comment by scd03132506** [comment]
这个问题修复好了吗？  safari现在无法推流，必须关闭这个UnifiedPlan才行

**Comment by scd03132506** [comment]
@geograous
