### ISSUE TITLE
在ts文件import pili-rtc-web时，提示 “wolfy87-eventemitter/EventEmitter“ has no default export.

### ISSUE THREAD

**Issue by xianjun-li** [pili-engineering/QNRTC-Web#59]
环境 ： typescript version: 3.6.3
提示如下：
```
node_modules/pili-rtc-web/build/core.d.ts(2,8): error TS1192: Module '"/Users/xxx/development/upfm/upfm-websocket/node_modules/wolfy87-eventemitter/EventEmitter"' has no default export.
node_modules/pili-rtc-web/build/device.d.ts(1,8): error TS1192: Module '"/Users/xxx/development/upfm/upfm-websocket/node_modules/wolfy87-eventemitter/EventEmitter"' has no default export.
```

**Comment by 41412179** [comment]
最后你怎么解决的，我也碰到了这个问题

**Comment by 41412179** [comment]
> 环境 ： typescript version: 3.6.3
> 提示如下：
> 
> ```
> node_modules/pili-rtc-web/build/core.d.ts(2,8): error TS1192: Module '"/Users/xxx/development/upfm/upfm-websocket/node_modules/wolfy87-eventemitter/EventEmitter"' has no default export.
> node_modules/pili-rtc-web/build/device.d.ts(1,8): error TS1192: Module '"/Users/xxx/development/upfm/upfm-websocket/node_modules/wolfy87-eventemitter/EventEmitter"' has no default export.
> ```

我也碰到这个问题了，怎么解决
