### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by caoyongxing1985** [pili-engineering/QNRTC-Web#6]
报错信息
plugin directly instead
i ｢wds｣: Project is running at http://localhost:4000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from F:\qiniu\workspace\QNRTC-Web-master\Demo\public
i ｢wds｣: 404s will fallback to /index.× ｢wdm｣:    720 modules

ERROR in F:\qiniu\workspace\QNRTC-Web-master\Demo\src\app\components\RemotePlayer\index.tsx
./app/components/RemotePlayer/index.tsx
[tsl] ERROR in F:\qiniu\workspace\QNRTC-Web-master\Demo\src\app\components\RemotePlayer\index.tsx(35,30)
      TS2345: Argument of type 'HTMLElement' is not assignable to parameter of type 'HTMLVideoElement | HTMLAudioElement'.
  Type 'HTMLElement' is not assignable to type 'HTMLAudioElement'.

ERROR in F:\qiniu\workspace\QNRTC-Web-master\Demo\src\app\components\RemotePlayer\index.tsx
./app/components/RemotePlayer/index.tsx
[tsl] ERROR in F:\qiniu\workspace\QNRTC-Web-master\Demo\src\app\components\RemotePlayer\index.tsx(41,30)
      TS2345: Argument of type 'HTMLElement' is not assignable to parameter of type 'HTMLVideoElement | HTMLAudioElement'.
  Type 'HTMLElement' is not assignable to type 'HTMLAudioElement'.

**Comment by disoul** [comment]
#7 抱歉，demo 中的依赖版本有误
