### ISSUE TITLE
运行demo报错type error怎么回事？

### ISSUE THREAD

**Issue by txlfreedom** [pili-engineering/QNRTC-Web#60]
Type error: Type 'string' is not assignable to type 'undefined'.  TS2322

    172 |                       type="number"
    173 |                       onChange={action((e: React.ChangeEvent<HTMLInputElement>) => {
  > 174 |                         this.camera[inputItem.key] = e.target.value;
        |                         ^
    175 |                       })}
    176 |                       value={this.camera[inputItem.key] as string}
    177 |                       required

![image](https://user-images.githubusercontent.com/40316627/66448304-a9afd900-ea83-11e9-8253-035bf7f56be8.png)

**Comment by brucebnu** [comment]
遇到相同的问题
