### ISSUE TITLE
UC浏览器手机版本 20201214，RTCPeerConnection类不存在，导致加入房间卡住

### ISSUE THREAD

**Issue by fengyang221** [pili-engineering/QNRTC-Web#76]
![提错](https://user-images.githubusercontent.com/29744953/103225225-7301ff00-4964-11eb-888d-a55495baed6f.png)

如上图所示，这里报该类不存在，其他版本浏览器正常，目前是UC手机浏览器出这个问题

**Comment by yaox023** [comment]
这个情况看应该是该浏览器不支持 RTC。
