### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by shaokeke** [pili-engineering/QNRTC-Web#77]
![image](https://user-images.githubusercontent.com/37448773/106855198-850b5600-66f7-11eb-91cc-639d8dcc2799.png)

**Comment by shaokeke** [comment]
'REACT_APP_LATEST_COMMIT_HASH' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by yaox023** [comment]
这就是设置了一个环境变量，windows 上设置方法与 mac 上不一致。修改为 window 上的写法，或者直接删除即可，

**Comment by daLeiStrive** [comment]
是的直接删除这个设置变量的就可以了
改成这个"start": "react-scripts start",
